
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true



decorations = "buttonless"


blur = false
opacity = 0.8

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

